name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r "acompanhamento medico/requirements.txt"

      - name: Install ruff
        run: pip install ruff

      - name: Install pytest
        run: pip install pytest

      - name: Run lint
        run: ruff check "acompanhamento medico"

      - name: Run tests
        run: |
          cd "acompanhamento medico"
          pytest
